In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
from scipy.signal import argrelextrema

from src import technical_indicators as ta
from VnFinance import vn_stock_market as vsm

In [3]:
df = pd.read_csv('cache/HPG.csv')
df

,Date,Open,High,Low,Close,Volume,Ticker,rsi_10,rsi_15,rsi_20,...,disparity_index_100,ma_10,upper_b10,lower_b10,ma_20,upper_b20,lower_b20,ma_30,upper_b30,lower_b30
0,2007-11-15,2663.0,2704.0,2267.0,2642.0,1306330,HPG,NaN,NaN,NaN,...,NaN,2642.00,NaN,NaN,2642.00,NaN,NaN,2642.000000,NaN,NaN
1,2007-11-16,2517.0,2517.0,2517.0,2517.0,248510,HPG,0.000000,0.000000,0.000000,...,NaN,2579.50,2667.888348,2491.111652,2579.50,2667.888348,2491.111652,2579.500000,2667.888348,2491.111652
2,2007-11-19,2392.0,2392.0,2392.0,2392.0,120480,HPG,0.000000,0.000000,0.000000,...,NaN,2517.00,2642.000000,2392.000000,2517.00,2642.000000,2392.000000,2517.000000,2642.000000,2392.000000
3,2007-11-20,2288.0,2288.0,2288.0,2288.0,58710,HPG,0.000000,0.000000,0.000000,...,NaN,2459.75,2613.134865,2306.365135,2459.75,2613.134865,2306.365135,2459.750000,2613.134865,2306.365135
4,2007-11-21,2184.0,2371.0,2184.0,2371.0,728080,HPG,6.317028,4.282075,3.238393,...,NaN,2442.00,2580.638018,2303.361982,2442.00,2580.638018,2303.361982,2442.000000,2580.638018,2303.361982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3733,2022-11-07,14550.0,14800.0,13700.0,13700.0,38281291,HPG,22.169672,24.975768,26.986712,...,-35.955870,15775.00,16995.712451,14554.287549,17040.00,18753.767779,15326.232221,17986.666667,20160.965338,15812.367995
3734,2022-11-08,13100.0,13700.0,13000.0,13150.0,46290133,HPG,20.239014,23.423533,25.662192,...,-38.236814,15380.00,16753.802509,14006.197491,16822.50,18738.875073,14906.124927,17678.333333,19861.050848,15495.615819
3735,2022-11-09,13200.0,13600.0,12950.0,13000.0,32797759,HPG,19.723719,23.007559,25.306513,...,-38.693704,14990.00,16436.029045,13543.970955,16537.50,18579.678597,14495.321403,17385.000000,19585.946113,15184.053887
3736,2022-11-10,12700.0,12800.0,12100.0,12100.0,79765322,HPG,16.886179,20.659477,23.274245,...,-42.702907,14460.00,15895.811811,13024.188189,16167.50,18312.461968,14022.538032,17066.666667,19319.493754,14813.839579
3737,2022-11-11,12300.0,12650.0,12000.0,12300.0,60729517,HPG,19.709734,22.533491,24.685495,...,-41.500999,14010.00,15331.573137,12688.426863,15810.00,17974.826479,13645.173521,16770.000000,19045.643145,14494.356855